/*
 * ListasDinamicas.java
 * 
 */
package labsesion7;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;

public class ListasDinamicas extends javax.swing.JFrame {

    /** Creates new form ListasDinamicas */
    public ListasDinamicas() {
        initComponents();
        jComboBoxMarcas.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxMarcas = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListExtras = new javax.swing.JList();
        jTextField1 = new javax.swing.JTextField();
        jLabelImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ListasDinámicas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Selecciona una marca de portátil y extras:");

        getMarcas();
        jComboBoxMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcasActionPerformed(evt);
            }
        });

        getExtras();
        jListExtras.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListExtrasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListExtras);

        jTextField1.setEditable(false);

        getImagen();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jLabelImg.getAccessibleContext().setAccessibleParent(jScrollPane1);

        setSize(new java.awt.Dimension(416, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private String marca_selec, extras;

    private void jComboBoxMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcasActionPerformed
        // TODO add your handling code here:
        //borramos texto
        jTextField1.setText("");
        //deseleccionamos el equipamiento
        jListExtras.clearSelection();
        //capturamos la marca seleccionada
        marca_selec = "Marca: " + (String) jComboBoxMarcas.getSelectedItem() + " # ";
        jTextField1.setText(marca_selec);
    }//GEN-LAST:event_jComboBoxMarcasActionPerformed

    private void jListExtrasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListExtrasValueChanged
        // TODO add your handling code here:
        //borramos texto e inicializamos equipamiento
        jTextField1.setText("");
        extras = " - ";
        //capturamos los items seleccionados
        // y los convertimos en cadena
        List<String> extras_selec = jListExtras.getSelectedValuesList();
        Iterator items = extras_selec.iterator();
        while (items.hasNext()) {
            extras += items.next() + " - ";
        }        
        //presentamos la selección de marca y equipamiento
        jTextField1.setText(marca_selec + extras);
    }//GEN-LAST:event_jListExtrasValueChanged

    // cargamos la imagen del portátil
    private void getImagen() {
        try {
            jLabelImg.setSize(130, 100);
            ImageIcon imagen = new ImageIcon("imagenes/portatil.jpg");
            //Se redimensiona
            ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(jLabelImg.getWidth(), jLabelImg.getHeight(), 1));
            jLabelImg.setIcon(imgRedimensionada);
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }

    // rellenamos las opciones de la lista desplegable
    private void getMarcas() {
        String cad;
        ArrayList<String> marcas = new ArrayList<String>();
        try {
            FileInputStream fis = new FileInputStream("marcas.txt");
            InputStreamReader is = new InputStreamReader(fis, "ISO-8859-1");
            BufferedReader br = new BufferedReader(is);
            while ((cad = br.readLine()) != null) {                
                marcas.add(cad);
            }
            //Cerramos el stream
            br.close();
            jComboBoxMarcas = new JComboBox(marcas.toArray());
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    // rellenamos las opciones de la lista
    private void getExtras() {
        String cad;
        ArrayList<String> extrasAL = new ArrayList<String>();
        try {
            FileInputStream fis = new FileInputStream("extras.txt");
            InputStreamReader is = new InputStreamReader(fis, "ISO-8859-1");
            BufferedReader br = new BufferedReader(is);
            while ((cad = br.readLine()) != null) {
                extrasAL.add(cad);
            }
            //Cerramos el stream
            br.close();
            jListExtras.setListData(extrasAL.toArray());
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ListasDinamicas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxMarcas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JList jListExtras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
