/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Historial;
import clases.Partida;
import clases.PartidaAlta;
import clases.PartidaBaja;
import clases.Torneo;
import clases.Usuario;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laura
 */
public class DificultadBaja extends javax.swing.JFrame {

    /**
     * Creates new form DificultadBaja
     */
    
    private static HashMap<String, clases.Historial> torneo;
    private static Usuario usuario;
    
    DefaultTableModel model = new DefaultTableModel();
    private static ArrayList<Historial> ordenado;
    
    public DificultadBaja(HashMap<String, clases.Historial> torne, Usuario usuari) {
        torneo = torne;
        usuario = usuari;
        initComponents();
        transparenciaBoton();
        this.setLocationRelativeTo(null);  //ajustarlo en el medio de la pantalla
        Historial historial = Torneo.devolverHistorial(torneo, usuario.getDNI());
        jLabelNombre_DificultadBaja.setText(usuario.getNombre());
        jLabelPuntos_DificultadBaja.setText(Integer.toString(historial.getPartidasBajas().getPuntos()));
        
        PartidaBaja p = historial.getPartidasBajas();
        ArrayList<Partida> array = p.getPartidasBajas();
        
        //creamos las columnas de la tabla
        model.addColumn("Puntos");
        model.addColumn("Terminada");
        model.addColumn("Ganada");
        this.jTable_DificultadBaja.setModel(model);

        for (int i = 0; i < array.size(); i++){
            String[] fila = new String[3];
            fila[0] = Integer.toString(array.get(i).getPuntos());
            fila[1] = Boolean.toString(array.get(i).isTerminada());
            fila[2] = Boolean.toString(array.get(i).isGanada());
            model.addRow(fila);
            
        }
    
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());  //cambiar logo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonTorneo_DificultadBaja = new javax.swing.JButton();
        botonAtras_DificultadBaja = new javax.swing.JButton();
        jLabelNombre_DificultadBaja = new javax.swing.JLabel();
        jLabelPuntos_DificultadBaja = new javax.swing.JLabel();
        jScroll_DificultadMedia = new javax.swing.JScrollPane();
        jTable_DificultadBaja = new javax.swing.JTable();
        fondo_DificultadBaja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonTorneo_DificultadBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTorneo_DificultadBajaMouseClicked(evt);
            }
        });
        getContentPane().add(botonTorneo_DificultadBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, 530, 70));

        botonAtras_DificultadBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtras_DificultadBajaMouseClicked(evt);
            }
        });
        getContentPane().add(botonAtras_DificultadBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 700, 170, 40));

        jLabelNombre_DificultadBaja.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        jLabelNombre_DificultadBaja.setForeground(new java.awt.Color(255, 204, 204));
        jLabelNombre_DificultadBaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelNombre_DificultadBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 810, 100));

        jLabelPuntos_DificultadBaja.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabelPuntos_DificultadBaja.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPuntos_DificultadBaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelPuntos_DificultadBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 240, 50));

        jTable_DificultadBaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScroll_DificultadMedia.setViewportView(jTable_DificultadBaja);

        getContentPane().add(jScroll_DificultadMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 301, 790, 300));

        fondo_DificultadBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dificultadBaja.jpg"))); // NOI18N
        getContentPane().add(fondo_DificultadBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtras_DificultadBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtras_DificultadBajaMouseClicked
        // TODO add your handling code here:
        HistorialInterfaz historial = new HistorialInterfaz(torneo, usuario);
        historial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtras_DificultadBajaMouseClicked

    private void botonTorneo_DificultadBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTorneo_DificultadBajaMouseClicked
        // TODO add your handling code here:
        TorneoBaja t = new TorneoBaja(torneo, usuario);
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonTorneo_DificultadBajaMouseClicked

    /**
     * Los botones serán transparentes
     */
    public void transparenciaBoton(){
        botonAtras_DificultadBaja.setOpaque(false);
        botonAtras_DificultadBaja.setContentAreaFilled(false);
        botonAtras_DificultadBaja.setBorderPainted(false);
        
        botonTorneo_DificultadBaja.setOpaque(false);
        botonTorneo_DificultadBaja.setContentAreaFilled(false);
        botonTorneo_DificultadBaja.setBorderPainted(false);
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras_DificultadBaja;
    private javax.swing.JButton botonTorneo_DificultadBaja;
    private javax.swing.JLabel fondo_DificultadBaja;
    private javax.swing.JLabel jLabelNombre_DificultadBaja;
    private javax.swing.JLabel jLabelPuntos_DificultadBaja;
    private javax.swing.JScrollPane jScroll_DificultadMedia;
    private javax.swing.JTable jTable_DificultadBaja;
    // End of variables declaration//GEN-END:variables
}
