/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Historial;
import clases.Usuario;
import java.util.HashMap;
import javax.swing.ImageIcon;

/**
 *
 * @author laura
 */
public class Dificultad extends javax.swing.JFrame {

    /**
     * Creates new form Dificultad
     */
    private static Usuario usuario;
    private static HashMap<String, clases.Historial> torneo;
    
    public Dificultad(HashMap<String, clases.Historial> torne, Usuario usuari) {
        usuario = usuari;
        torneo = torne;
        initComponents();
        transparenciaBoton();
        this.setLocationRelativeTo(null);  //ajustarlo en el medio de la pantalla
        
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());  //cambiar logo
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonBaja_Dificultad = new javax.swing.JButton();
        botonMedia_Dificultad = new javax.swing.JButton();
        botonAlta_Dificultad = new javax.swing.JButton();
        botonImposible_Dificultad = new javax.swing.JButton();
        botonAtras_Dificultad = new javax.swing.JButton();
        fondoDificultad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonBaja_Dificultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBaja_DificultadMouseClicked(evt);
            }
        });
        getContentPane().add(botonBaja_Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 510, 60));

        botonMedia_Dificultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMedia_DificultadMouseClicked(evt);
            }
        });
        getContentPane().add(botonMedia_Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 510, 60));

        botonAlta_Dificultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAlta_DificultadMouseClicked(evt);
            }
        });
        getContentPane().add(botonAlta_Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 510, 60));

        botonImposible_Dificultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonImposible_DificultadMouseClicked(evt);
            }
        });
        getContentPane().add(botonImposible_Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 510, 70));

        botonAtras_Dificultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtras_DificultadMouseClicked(evt);
            }
        });
        getContentPane().add(botonAtras_Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 655, 170, 30));

        fondoDificultad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dificultad.jpg"))); // NOI18N
        getContentPane().add(fondoDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBaja_DificultadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBaja_DificultadMouseClicked
        // TODO add your handling code here:
        PartidaInterfaz p = new PartidaInterfaz(torneo, usuario, "BAJA");
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonBaja_DificultadMouseClicked

    private void botonMedia_DificultadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMedia_DificultadMouseClicked
        // TODO add your handling code here:
        PartidaInterfaz p = new PartidaInterfaz(torneo, usuario, "MEDIA");
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonMedia_DificultadMouseClicked

    private void botonAlta_DificultadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAlta_DificultadMouseClicked
        // TODO add your handling code here:
        PartidaInterfaz p = new PartidaInterfaz(torneo, usuario, "ALTA");
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAlta_DificultadMouseClicked

    private void botonImposible_DificultadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImposible_DificultadMouseClicked
        // TODO add your handling code here:
        PartidaInterfaz p = new PartidaInterfaz(torneo, usuario, "IMPOSIBLE");
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonImposible_DificultadMouseClicked

    private void botonAtras_DificultadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtras_DificultadMouseClicked
        // TODO add your handling code here:
        IniciarSesion inicioSesion = new IniciarSesion();
        inicioSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtras_DificultadMouseClicked

    /**
     * Los botones serán transparentes
     */
    public void transparenciaBoton() {

        botonBaja_Dificultad.setOpaque(false);
        botonBaja_Dificultad.setContentAreaFilled(false);
        botonBaja_Dificultad.setBorderPainted(false);

        botonMedia_Dificultad.setOpaque(false);
        botonMedia_Dificultad.setContentAreaFilled(false);
        botonMedia_Dificultad.setBorderPainted(false);

        botonAlta_Dificultad.setOpaque(false);
        botonAlta_Dificultad.setContentAreaFilled(false);
        botonAlta_Dificultad.setBorderPainted(false);

        botonImposible_Dificultad.setOpaque(false);
        botonImposible_Dificultad.setContentAreaFilled(false);
        botonImposible_Dificultad.setBorderPainted(false);

        botonAtras_Dificultad.setOpaque(false);
        botonAtras_Dificultad.setContentAreaFilled(false);
        botonAtras_Dificultad.setBorderPainted(false);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlta_Dificultad;
    private javax.swing.JButton botonAtras_Dificultad;
    private javax.swing.JButton botonBaja_Dificultad;
    private javax.swing.JButton botonImposible_Dificultad;
    private javax.swing.JButton botonMedia_Dificultad;
    private javax.swing.JLabel fondoDificultad;
    // End of variables declaration//GEN-END:variables
}
