/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Historial;
import clases.Partida;
import clases.PartidaBaja;
import clases.Torneo;
import clases.Usuario;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laura
 */
public class DificultadImposible extends javax.swing.JFrame {

    /**
     * Creates new form DificultadImposible
     */
    private static HashMap<String, clases.Historial> torneo;
    private static Usuario usuario;
    DefaultTableModel model = new DefaultTableModel();
    private static ArrayList<Historial> ordenado;

    public DificultadImposible(HashMap<String, clases.Historial> torne, Usuario usuari) {
        torneo = torne;
        usuario = usuari;
        initComponents();
        transparenciaBoton();
        this.setLocationRelativeTo(null);  //ajustarlo en el medio de la pantalla

        Historial historial = Torneo.devolverHistorial(torneo, usuario.getDNI());
        jLabelNombre_DificultadImposible.setText(usuario.getNombre());
        jLabelPuntos_DificultadImposible.setText(Integer.toString(historial.getPartidasImposibles().getPuntos()));

        PartidaBaja p = historial.getPartidasBajas();
        ArrayList<Partida> array = p.getPartidasBajas();
        
        //creamos las columnas de la tabla
        model.addColumn("Puntos");
        model.addColumn("Terminada");
        model.addColumn("Ganada");
        this.jTable_DificultadImposible.setModel(model);

        for (int i = 0; i < array.size(); i++){
            String[] fila = new String[3];
            fila[0] = Integer.toString(array.get(i).getPuntos());
            fila[1] = Boolean.toString(array.get(i).isTerminada());
            fila[2] = Boolean.toString(array.get(i).isGanada());
            model.addRow(fila);
            
        }
        
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());  //cambiar logo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonTorneo_DificultadImposible = new javax.swing.JButton();
        botonAtras_DificultadImposible = new javax.swing.JButton();
        jLabelNombre_DificultadImposible = new javax.swing.JLabel();
        jLabelPuntos_DificultadImposible = new javax.swing.JLabel();
        jScroll_DificultadMedia = new javax.swing.JScrollPane();
        jTable_DificultadImposible = new javax.swing.JTable();
        fondo_DificultadImposible = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonTorneo_DificultadImposible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTorneo_DificultadImposibleMouseClicked(evt);
            }
        });
        getContentPane().add(botonTorneo_DificultadImposible, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, 530, 60));

        botonAtras_DificultadImposible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtras_DificultadImposibleMouseClicked(evt);
            }
        });
        getContentPane().add(botonAtras_DificultadImposible, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 700, 170, 30));

        jLabelNombre_DificultadImposible.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        jLabelNombre_DificultadImposible.setForeground(new java.awt.Color(255, 204, 204));
        jLabelNombre_DificultadImposible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelNombre_DificultadImposible, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 810, 90));

        jLabelPuntos_DificultadImposible.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabelPuntos_DificultadImposible.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPuntos_DificultadImposible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelPuntos_DificultadImposible, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 240, 60));

        jTable_DificultadImposible.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScroll_DificultadMedia.setViewportView(jTable_DificultadImposible);

        getContentPane().add(jScroll_DificultadMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 301, 790, 300));

        fondo_DificultadImposible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dificultadImposible.jpg"))); // NOI18N
        getContentPane().add(fondo_DificultadImposible, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtras_DificultadImposibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtras_DificultadImposibleMouseClicked
        // TODO add your handling code here:
        HistorialInterfaz historial = new HistorialInterfaz(torneo, usuario);
        historial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtras_DificultadImposibleMouseClicked

    private void botonTorneo_DificultadImposibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTorneo_DificultadImposibleMouseClicked
        // TODO add your handling code here:
        TorneoImposible t = new TorneoImposible(torneo, usuario);
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonTorneo_DificultadImposibleMouseClicked

    /**
     * Los botones serán transparentes
     */
    public void transparenciaBoton() {
        botonAtras_DificultadImposible.setOpaque(false);
        botonAtras_DificultadImposible.setContentAreaFilled(false);
        botonAtras_DificultadImposible.setBorderPainted(false);

        botonTorneo_DificultadImposible.setOpaque(false);
        botonTorneo_DificultadImposible.setContentAreaFilled(false);
        botonTorneo_DificultadImposible.setBorderPainted(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras_DificultadImposible;
    private javax.swing.JButton botonTorneo_DificultadImposible;
    private javax.swing.JLabel fondo_DificultadImposible;
    private javax.swing.JLabel jLabelNombre_DificultadImposible;
    private javax.swing.JLabel jLabelPuntos_DificultadImposible;
    private javax.swing.JScrollPane jScroll_DificultadMedia;
    private javax.swing.JTable jTable_DificultadImposible;
    // End of variables declaration//GEN-END:variables
}
