/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Historial;
import clases.Torneo;
import clases.Usuario;
import java.awt.Image;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author laura
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IntroIniciarSesion
     */
    private HashMap<String, Historial> torneo = Torneo.torneoLleno();

    public IniciarSesion() {
        initComponents();
        transparenciaBoton();
        this.setLocationRelativeTo(null);  //ajustarlo en el medio de la pantalla

        HashMap<String, Historial> torneo = Torneo.crearTorneo();

        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());  //cambiar logo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIniciarSesion_IniciarSesion = new javax.swing.JButton();
        textFieldDNI_IniciarSesion = new javax.swing.JTextField();
        botonRegistrarse_IniciarSesion = new javax.swing.JButton();
        botonSalir_IniciarSesion = new javax.swing.JButton();
        fondoIniciarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonIniciarSesion_IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIniciarSesion_IniciarSesionMouseClicked(evt);
            }
        });
        botonIniciarSesion_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesion_IniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(botonIniciarSesion_IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 590, 60));

        textFieldDNI_IniciarSesion.setFont(new java.awt.Font("Cooper Black", 0, 28)); // NOI18N
        textFieldDNI_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDNI_IniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldDNI_IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 372, 390, 40));

        botonRegistrarse_IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarse_IniciarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(botonRegistrarse_IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 590, 60));

        botonSalir_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalir_IniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir_IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 590, 140, 30));

        fondoIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iniciarSesion.png"))); // NOI18N
        getContentPane().add(fondoIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDNI_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDNI_IniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDNI_IniciarSesionActionPerformed

    private void botonSalir_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalir_IniciarSesionActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalir_IniciarSesionActionPerformed

    private void botonIniciarSesion_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesion_IniciarSesionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_botonIniciarSesion_IniciarSesionActionPerformed

    /**
     * Conecta IniciarSesion con Registro
     *
     * @param evt
     */
    private void botonRegistrarse_IniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarse_IniciarSesionMouseClicked
        // TODO add your handling code here:
        Registro registro = new Registro(torneo);
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRegistrarse_IniciarSesionMouseClicked

    private void botonIniciarSesion_IniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarSesion_IniciarSesionMouseClicked
        // TODO add your handling code here:
        String dniString = textFieldDNI_IniciarSesion.getText();
        if (Usuario.comprobarDNI(dniString) == false) {
            JOptionPane.showMessageDialog(this, "DNI FALSO");
            textFieldDNI_IniciarSesion.setText("");
        } else {
            if (Torneo.comprobarUsuarioRegistrado(torneo, dniString)) { //ususario registrado
                Historial historial = Torneo.devolverHistorial(torneo, dniString);
                SesionIniciada sI = new SesionIniciada(torneo, historial.getUsuario());
                sI.setVisible(true);
                this.dispose();
            } else { //usuario no registrado
                JOptionPane.showMessageDialog(this, "Usuario no registrado.");
                textFieldDNI_IniciarSesion.setText("");
            }
        }
    }//GEN-LAST:event_botonIniciarSesion_IniciarSesionMouseClicked

    /**
     * Los botones serán transparentes
     */
    public void transparenciaBoton() {
        botonIniciarSesion_IniciarSesion.setOpaque(false);
        botonIniciarSesion_IniciarSesion.setContentAreaFilled(false);
        botonIniciarSesion_IniciarSesion.setBorderPainted(false);

        botonRegistrarse_IniciarSesion.setOpaque(false);
        botonRegistrarse_IniciarSesion.setContentAreaFilled(false);
        botonRegistrarse_IniciarSesion.setBorderPainted(false);

        botonSalir_IniciarSesion.setOpaque(false);
        botonSalir_IniciarSesion.setContentAreaFilled(false);
        botonSalir_IniciarSesion.setBorderPainted(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSesion_IniciarSesion;
    private javax.swing.JButton botonRegistrarse_IniciarSesion;
    private javax.swing.JButton botonSalir_IniciarSesion;
    private javax.swing.JLabel fondoIniciarSesion;
    private javax.swing.JTextField textFieldDNI_IniciarSesion;
    // End of variables declaration//GEN-END:variables
}
