/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Usuario;
import java.util.HashMap;
import javax.swing.ImageIcon;

/**
 *
 * @author laura
 */
public class PartidasGuardadas extends javax.swing.JFrame {

    /**
     * Creates new form PartidasGuardadas
     */
    private static HashMap<String, clases.Historial> torneo;
    private static Usuario usuario;
    
    public PartidasGuardadas(HashMap<String, clases.Historial> torne, Usuario usuari) {
        torneo = torne;
        usuario = usuari;
        initComponents();
        transparenciaBoton();
        this.setLocationRelativeTo(null);  //ajustarlo en el medio de la pantalla
    
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());  //cambiar logo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAtras_PartidasGuardadas = new javax.swing.JButton();
        fondo_PartidasGuardadas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAtras_PartidasGuardadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtras_PartidasGuardadasMouseClicked(evt);
            }
        });
        getContentPane().add(botonAtras_PartidasGuardadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 660, 190, 40));

        fondo_PartidasGuardadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/partidasGuardadas.jpg"))); // NOI18N
        getContentPane().add(fondo_PartidasGuardadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtras_PartidasGuardadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtras_PartidasGuardadasMouseClicked
        // TODO add your handling code here:
        SesionIniciada s = new SesionIniciada(torneo, usuario);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtras_PartidasGuardadasMouseClicked

    /**
     * Los botones serán transparentes
     */
    public void transparenciaBoton(){        
        botonAtras_PartidasGuardadas.setOpaque(false);
        botonAtras_PartidasGuardadas.setContentAreaFilled(false);
        botonAtras_PartidasGuardadas.setBorderPainted(false);
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras_PartidasGuardadas;
    private javax.swing.JLabel fondo_PartidasGuardadas;
    // End of variables declaration//GEN-END:variables
}
