/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Historial;
import clases.Torneo;
import clases.Usuario;
import static clases.Usuario.prepararDNI;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author laura
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form RegistroInterfaz
     */
    private static HashMap<String, Historial> torneo;

    public Registro(HashMap<String, Historial> torne) {
        torneo = torne;
        initComponents();
        transparenciaBoton();
        this.setLocationRelativeTo(null);  //ajustarlo en el medio de la pantalla

        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());  //cambiar logo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldNombreRegistro = new javax.swing.JTextField();
        textFieldDniRegistro = new javax.swing.JTextField();
        botonRegistrarse_Registro = new javax.swing.JButton();
        botonAtras_Registro = new javax.swing.JButton();
        fondoRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldNombreRegistro.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        textFieldNombreRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldNombreRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 250, 30));

        textFieldDniRegistro.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        getContentPane().add(textFieldDniRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 310, 30));

        botonRegistrarse_Registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarse_RegistroMouseClicked(evt);
            }
        });
        getContentPane().add(botonRegistrarse_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 390, 40));

        botonAtras_Registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtras_RegistroMouseClicked(evt);
            }
        });
        getContentPane().add(botonAtras_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 290, 30));

        fondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro.jpg"))); // NOI18N
        getContentPane().add(fondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarse_RegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarse_RegistroMouseClicked
        // TODO add your handling code here:
        String nombre = textFieldNombreRegistro.getText();
        String dniString = textFieldDniRegistro.getText();

        Usuario usuario = new Usuario(dniString, nombre);
        if (Usuario.comprobarDNI(dniString)) {
            String dni = Usuario.prepararDNI(textFieldDniRegistro.getText());
            usuario = new Usuario(dni, nombre);
            if (Torneo.comprobarUsuarioRegistrado(torneo, dni) == false) {  //si el usuario NO está registrado

                Torneo.aniadirUsuario(torneo, usuario);
                //cambio interfaz
                Registrado r = new Registrado(torneo, usuario);
                r.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Este usuario ya está registrado.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "DNI falso.");
            textFieldDniRegistro.setText("");
        }

    }//GEN-LAST:event_botonRegistrarse_RegistroMouseClicked

    /**
     * Conecta Registro con IniciarSesion
     *
     * @param evt
     */
    private void botonAtras_RegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtras_RegistroMouseClicked
        // TODO add your handling code here:
        IniciarSesion inicioSesion = new IniciarSesion();
        inicioSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtras_RegistroMouseClicked

    private void textFieldNombreRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreRegistroActionPerformed

    /**
     * Los botones serán transparentes
     */
    public void transparenciaBoton() {
        botonRegistrarse_Registro.setOpaque(false);
        botonRegistrarse_Registro.setContentAreaFilled(false);
        botonRegistrarse_Registro.setBorderPainted(false);

        botonAtras_Registro.setOpaque(false);
        botonAtras_Registro.setContentAreaFilled(false);
        botonAtras_Registro.setBorderPainted(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras_Registro;
    private javax.swing.JButton botonRegistrarse_Registro;
    private javax.swing.JLabel fondoRegistro;
    private javax.swing.JTextField textFieldDniRegistro;
    private javax.swing.JTextField textFieldNombreRegistro;
    // End of variables declaration//GEN-END:variables
}
