/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Historial;
import clases.Usuario;
import java.util.HashMap;
import javax.swing.ImageIcon;

/**
 *
 * @author laura
 */
public class Registrado extends javax.swing.JFrame {

    private static Usuario usuario;
    private static HashMap<String, clases.Historial> torneo;

    /**
     * Creates new form Registrado
     */
    public Registrado(HashMap<String, clases.Historial> torne, Usuario usuari) {
        usuario = usuari;
        torneo = torne;
        initComponents();
        transparenciaBoton();
        this.setLocationRelativeTo(null);  //ajustarlo en el medio de la pantalla

        jLabelNombre_Registrado.setText(usuario.getNombre());

        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());  //cambiar logo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAtras_Registrado = new javax.swing.JButton();
        botonPartidaNueva_Registrado = new javax.swing.JButton();
        jLabelNombre_Registrado = new javax.swing.JLabel();
        fondo_Registrado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAtras_Registrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtras_RegistradoMouseClicked(evt);
            }
        });
        getContentPane().add(botonAtras_Registrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 380, 40));

        botonPartidaNueva_Registrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPartidaNueva_RegistradoMouseClicked(evt);
            }
        });
        getContentPane().add(botonPartidaNueva_Registrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 390, 40));

        jLabelNombre_Registrado.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        jLabelNombre_Registrado.setForeground(new java.awt.Color(255, 204, 204));
        jLabelNombre_Registrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelNombre_Registrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 430, 60));

        fondo_Registrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrado.jpg"))); // NOI18N
        getContentPane().add(fondo_Registrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtras_RegistradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtras_RegistradoMouseClicked
        // TODO add your handling code here:
        IniciarSesion iniciarSesion = new IniciarSesion();
        iniciarSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtras_RegistradoMouseClicked

    private void botonPartidaNueva_RegistradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPartidaNueva_RegistradoMouseClicked
        // TODO add your handling code here:
        Dificultad dificultad = new Dificultad(torneo, usuario);
        dificultad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonPartidaNueva_RegistradoMouseClicked

    /**
     * Los botones serán transparentes
     */
    public void transparenciaBoton() {
        botonAtras_Registrado.setOpaque(false);
        botonAtras_Registrado.setContentAreaFilled(false);
        botonAtras_Registrado.setBorderPainted(false);

        botonPartidaNueva_Registrado.setOpaque(false);
        botonPartidaNueva_Registrado.setContentAreaFilled(false);
        botonPartidaNueva_Registrado.setBorderPainted(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras_Registrado;
    private javax.swing.JButton botonPartidaNueva_Registrado;
    private javax.swing.JLabel fondo_Registrado;
    private javax.swing.JLabel jLabelNombre_Registrado;
    // End of variables declaration//GEN-END:variables

}
