/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Historial;
import clases.Objeto;
import clases.Partida;
import clases.Torneo;
import clases.Usuario;
import java.util.HashMap;
import javax.swing.ImageIcon;

/**
 *
 * @author laura
 */
public class SalirJuego extends javax.swing.JFrame {

    /**
     * Creates new form SalirJuego
     */
    
    private static Usuario usuario;
    private static HashMap<String, clases.Historial> torneo;
    private static String dificultad = null;
    private static Objeto[][] tablero;
    private static int[] puntos;
    private static boolean terminada;
    private static boolean ganada;
    
    //torneo, usuario, dificultad, tablero
    public SalirJuego(HashMap<String, clases.Historial> torne, Usuario usuari, String dificulta, Objeto[][] tabler, int[] punto, boolean terminad, boolean ganad) {
        usuario = usuari;
        torneo = torne;
        dificultad = dificulta;
        tablero = tabler;
        puntos = punto;
        terminada = terminad;
        ganada = ganad;
        initComponents();
        transparenciaBoton();
        this.setLocationRelativeTo(null);  //ajustarlo en el medio de la pantalla
        
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());  //cambiar logo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGuardarPartida_SalirJuego = new javax.swing.JButton();
        botonNoGuardarPartida_SalirJuego = new javax.swing.JButton();
        fondoSalirJuego = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonGuardarPartida_SalirJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarPartida_SalirJuegoMouseClicked(evt);
            }
        });
        getContentPane().add(botonGuardarPartida_SalirJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 50, 420, 50));

        botonNoGuardarPartida_SalirJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNoGuardarPartida_SalirJuegoMouseClicked(evt);
            }
        });
        getContentPane().add(botonNoGuardarPartida_SalirJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 135, 410, 50));

        fondoSalirJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoSalirModoJuego.jpg"))); // NOI18N
        getContentPane().add(fondoSalirJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNoGuardarPartida_SalirJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNoGuardarPartida_SalirJuegoMouseClicked
        // TODO add your handling code here:
        IniciarSesion inicioSesion = new IniciarSesion();
        inicioSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonNoGuardarPartida_SalirJuegoMouseClicked

    private void botonGuardarPartida_SalirJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarPartida_SalirJuegoMouseClicked
        // TODO add your handling code here:
        Historial historial = Torneo.devolverHistorial(torneo, usuario.getDNI());
        Partida partida = new Partida(puntos[0], terminada, ganada, tablero);
        if (dificultad == "BAJA"){
            historial.getPartidasBajas().getPartidasBajas().add(partida);
        } else if (dificultad == "MEDIA"){
            historial.getPartidasMedias().getPartidasMedias().add(partida);
        } else if (dificultad == "ALTA"){
            historial.getPartidasAltas().getPartidasAltas().add(partida);
        } else if (dificultad == "IMPOSIBLE"){
            historial.getPartidasImposibles().getPartidasImposibles().add(partida);
        } 
        
        IniciarSesion inicioSesion = new IniciarSesion();
        inicioSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonGuardarPartida_SalirJuegoMouseClicked

    /**
     * Los botones serán transparentes
     */
    public void transparenciaBoton(){
        botonGuardarPartida_SalirJuego.setOpaque(false);
        botonGuardarPartida_SalirJuego.setContentAreaFilled(false);
        botonGuardarPartida_SalirJuego.setBorderPainted(false);
        
        botonNoGuardarPartida_SalirJuego.setOpaque(false);
        botonNoGuardarPartida_SalirJuego.setContentAreaFilled(false);
        botonNoGuardarPartida_SalirJuego.setBorderPainted(false);
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarPartida_SalirJuego;
    private javax.swing.JButton botonNoGuardarPartida_SalirJuego;
    private javax.swing.JLabel fondoSalirJuego;
    // End of variables declaration//GEN-END:variables
}
